[build]
  command = """
    mkdir -p public
    echo '<html><body></body></html>' > public/index.html
  """
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handleSubdomain"
  status = 200
  force = true

[[redirects]]
  from = "https://www.*"
  to = "https://:splat"
  status = 301
  force = true