[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handleSubdomain"
  status = 200
  force = true

[[redirects]]
  from = "https://www.*"
  to = "https://:splat"
  status = 301
  force = true